services:
  - type: web
    name: ci-cd-backend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: docker/Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        # Replace this after frontend is deployed (e.g., https://yourapp.vercel.app)
        value: http://localhost:3001
    healthCheckPath: /health
    autoDeploy: true

